; This pattern is generated by ./bin/playfield.exe
; Bytes 0 and 15 must be the same.
PFPattern
    dc.b $6d, $e5, $b6, $0e, $c0, $a0, $b6, $ec
    dc.b $0d, $83, $09, $3a, $a0, $7e, $49, $6d
;PF_ROW_HEIGHT = * - PFPattern
    ; Doubled up for speed reasons.
    dc.b $6d, $e5, $b6, $0e, $c0, $a0, $b6, $ec
    dc.b $0d, $83, $09, $3a, $a0, $7e, $49, $6d

;; test pattern
;PFPattern
;    dc.b $ff, $00, $00, $00, $00, $00, $00, $00
;    dc.b $00, $00, $00, $00, $00, $00, $00, $ff
;PF_ROW_HEIGHT = * - PFPattern
;    dc.b $ff, $00, $00, $00, $00, $00, $00, $00
;    dc.b $00, $00, $00, $00, $00, $00, $00, $ff
